### ISSUE TITLE
neutron recipes on compute nodes should not look at attributes from neutron-server nodes

### ISSUE THREAD

**Issue by vuntz** [sap-oc/crowbar-openstack#11]
It could be that an attribute gets added in a migration to the neutron proposal, and this will become visible on the neutron-server node only when chef has run. However, if chef runs on compute nodes first, it will not find the attribute. This could result in the wrong config on the compute nodes for a period of time.

The fix is to adopt the data bag config item work, and extend it (see https://github.com/crowbar/crowbar-openstack/pull/718)

## Backport Databag work
 - [x] Backport crowbar/crowbar-core#954
 - [x] Backport crowbar/crowbar#2302
 - [x] Backport crowbar/crowbar-core#947
 - [x] Backport crowbar/crowbar-openstack#718

## Fix the issue
 - [ ] @vuntz could you provide some description what would be the work to be done?

**Comment by matelakat** [comment]
- sap-oc/crowbar-core#22 backports:
   - crowbar/crowbar-core#947
   - crowbar/crowbar-core#954
 - sap-oc/crowbar#2 backports:
   -  crowbar/crowbar#2302
 - sap-oc/crowbar-openstack#31 backports:
   - crowbar/crowbar-openstack#718

**Comment by vuntz** [comment]
> @vuntz could you provide some description what would be the work to be done?

If you look at the neutron cookbook, you'll see some recipes which are run on compute nodes too. These ones are the problematic ones. We do something like `neutron = search node with role neutron-server`; but in case a schema migration happened and chef hasn't run yet on the neutron-server, the attributes will be wrong. So we should instead do something like `neutron = Role.load("neutron-config-default")` and read the attributes directly from the role.

**Comment by vuntz** [comment]
Note that this is a bit of a special case: usually, the data bag config item that you backported would be enough; but the problem is that the recipes need to look at, basically, all attributes of the proposal. Which is way more than what the data bag config item contains.

Of course, one alternative is to make the data bag config item contain a copy of the attributes.

**Comment by tpatzig** [comment]
I think https://github.com/sap-oc/crowbar-openstack/issues/34 is the same, @vuntz do you agree?

**Comment by vuntz** [comment]
> I think #34 is the same, @vuntz do you agree?

Not completely, unfortunatel.

**Comment by vuntz** [comment]
@mkoderer this is a true issue, but also a very edge case that wouldn't occur again unless more attributes are added to the neutron barclamp. I'm tempted to drop the critical tag here.
